import {
  SOFT_ATTACK,
  HARD_ATTACK,
  HEAT_ATTACK,
  DODGE,
  COMMAND,
  COOLING
} from './diceNames'

import {
  TRAITS
} from './traits'

export const LCT_1V = {
  name: 'Locust',
  model: 'LCT_1V',
  fullName: 'Locust-1V',
  imageSource: '/img/mechs/1_LOCUST.jpg',
  tons: 20,
  maxStructure: 6,
  currentStructure: 6,
  originalBaseDice: [SOFT_ATTACK, DODGE, DODGE],
  baseDice: [SOFT_ATTACK, DODGE, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const WSP_1A = {
  name: 'Wasp',
  model: 'WSP_1A',
  fullName: 'Wasp-1A',
  imageSource: '/img/mechs/2_WASP.jpg',
  tons: 20,
  maxStructure: 5,
  currentStructure: 5,
  originalBaseDice: [SOFT_ATTACK, DODGE, DODGE],
  baseDice: [SOFT_ATTACK, DODGE, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const STG_3R = {
  name: 'Stinger',
  model: 'STG_3R',
  fullName: 'Stinger-3R',
  imageSource: '/img/mechs/3_STINGER.jpg',
  tons: 20,
  maxStructure: 5,
  currentStructure: 5,
  originalBaseDice: [SOFT_ATTACK, DODGE, DODGE],
  baseDice: [SOFT_ATTACK, DODGE, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const COM_2D = {
  name: 'Commando',
  model: 'COM_2D',
  fullName: 'Commando-2D',
  imageSource: '/img/mechs/4_COMMANDO.jpg',
  tons: 25,
  maxStructure: 7,
  currentStructure: 7,
  originalBaseDice: [SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, DODGE],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const JVN_10N = {
  name: 'Javelin',
  model: 'JVN_10N',
  fullName: 'Javelin-10N',
  imageSource: '/img/mechs/5_JAVELIN.jpg',
  tons: 30,
  maxStructure: 8,
  currentStructure: 8,
  originalBaseDice: [DODGE, DODGE],
  baseDice: [DODGE, DODGE],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const SDR_5V = {
  name: 'Spider',
  model: 'SDR_5V',
  fullName: 'Spider-5V',
  imageSource: '/img/mechs/6_SPIDER.jpg',
  tons: 30,
  maxStructure: 7,
  currentStructure: 7,
  originalBaseDice: [SOFT_ATTACK, DODGE, DODGE],
  baseDice: [SOFT_ATTACK, DODGE, DODGE],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [TRAITS.FAULTY_EJECTION],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const UM_R60 = {
  name: 'Urbanmech',
  model: 'UM_R60',
  fullName: 'Urbanmech-R60',
  imageSource: '/img/mechs/7_URBANMECH.jpg',
  tons: 30,
  maxStructure: 10,
  currentStructure: 10,
  originalBaseDice: [HARD_ATTACK],
  baseDice: [HARD_ATTACK],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const VLK_QA = {
  name: 'Valkyrie',
  model: 'VLK_QA',
  fullName: 'Valkyrie-QA',
  imageSource: '/img/mechs/8_VALKYRIE.jpg',
  tons: 30,
  maxStructure: 10,
  currentStructure: 10,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const FS9_H = {
  name: 'Firestarter',
  model: 'FS9_H',
  fullName: 'Firestarter-9-H',
  imageSource: '/img/mechs/9_FIRESTARTER.jpg',
  tons: 35,
  maxStructure: 10,
  currentStructure: 10,
  originalBaseDice: [HEAT_ATTACK, HEAT_ATTACK],
  baseDice: [HEAT_ATTACK, HEAT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK, DODGE],
  optionalDice: [SOFT_ATTACK, DODGE],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const JR7_D = {
  name: 'Jenner',
  model: 'JR7_D',
  fullName: 'Jenner-7-D',
  imageSource: '/img/mechs/10_JENNER.jpg',
  tons: 35,
  maxStructure: 8,
  currentStructure: 8,
  originalBaseDice: [SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, DODGE],
  originalOptionalDice: [DODGE, HARD_ATTACK],
  optionalDice: [DODGE, HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const OTT_7J = {
  name: 'Ostscout',
  model: 'OTT_7J',
  fullName: 'Ostscout-7J',
  imageSource: '/img/mechs/11_OSTSCOUT.jpg',
  tons: 35,
  maxStructure: 9,
  currentStructure: 9,
  originalBaseDice: [SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, DODGE],
  originalOptionalDice: [DODGE],
  optionalDice: [DODGE],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const PNT_9R = {
  name: 'Panther',
  model: 'PNT_9R',
  fullName: 'Panther-9R',
  imageSource: '/img/mechs/12_PANTHER.jpg',
  tons: 35,
  maxStructure: 11,
  currentStructure: 11,
  originalBaseDice: [HARD_ATTACK, DODGE],
  baseDice: [HARD_ATTACK, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 1,
  originalTargets: 1,
  destroyed: false
}

export const ASN_21 = {
  name: 'Assassin',
  model: 'ASN_21',
  fullName: 'Assassin-21',
  imageSource: '/img/mechs/13_ASSASSIN.jpg',
  tons: 40,
  maxStructure: 9,
  currentStructure: 9,
  originalBaseDice: [SOFT_ATTACK, DODGE, DODGE],
  baseDice: [SOFT_ATTACK, DODGE, DODGE],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [TRAITS.FAULTY_EJECTION],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const CDA_2A = {
  name: 'Cicada',
  model: 'CDA_2A',
  fullName: 'Cicada-2A',
  imageSource: '/img/mechs/14_CICADA.jpg',
  tons: 40,
  maxStructure: 9,
  currentStructure: 9,
  originalBaseDice: [SOFT_ATTACK, DODGE ],
  baseDice: [SOFT_ATTACK, DODGE],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const CLNT_2_3T = {
  name: 'Clint',
  model: 'CLNT_2_3T',
  fullName: 'Clint-2-3T',
  imageSource: '/img/mechs/15_CLINT.jpg',
  tons: 40,
  maxStructure: 9,
  currentStructure: 9,
  originalBaseDice: [COMMAND, DODGE ],
  baseDice: [COMMAND, DODGE],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const HER_2S = {
  name: 'Hermes II',
  model: 'HER_2S',
  fullName: 'Hermes-2S',
  imageSource: '/img/mechs/16_HERMESII.jpg',
  tons: 40,
  maxStructure: 12,
  currentStructure: 12,
  originalBaseDice: [SOFT_ATTACK, HEAT_ATTACK, COMMAND],
  baseDice: [SOFT_ATTACK, HEAT_ATTACK, COMMAND],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const VL_2T = {
  name: 'Vulcan',
  model: 'VL_2T',
  fullName: 'Vulcan-2T',
  imageSource: '/img/mechs/17_VULCAN.jpg',
  tons: 40,
  maxStructure: 10,
  currentStructure: 10,
  originalBaseDice: [SOFT_ATTACK, HEAT_ATTACK],
  baseDice: [SOFT_ATTACK, HEAT_ATTACK],
  originalOptionalDice: [DODGE],
  optionalDice: [DODGE],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const WTH_1 = {
  name: 'Whitworth',
  model: 'WTH_1',
  fullName: 'Whitworth-1',
  imageSource: '/img/mechs/18_WHITWORTH.jpg',
  tons: 40,
  maxStructure: 13,
  currentStructure: 13,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const BJ_1 = {
  name: 'Blackjack',
  model: 'BJ_1',
  fullName: 'Blackjack-1',
  imageSource: '/img/mechs/19_BLACKJACK.jpg',
  tons: 40,
  maxStructure: 14,
  currentStructure: 14,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const HCT_3F = {
  name: 'Hatchetman',
  model: 'HCT_3F',
  fullName: 'Hatchetman-3F',
  imageSource: '/img/mechs/20_HATCHETMAN.jpg',
  tons: 45,
  maxStructure: 12,
  currentStructure: 12,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [TRAITS.URBAN_COMBAT, TRAITS.EFFICIENT_EJECTION],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const PHX_1 = {
  name: 'Phoenix Hawk',
  model: 'PHX_1',
  fullName: 'Phoenix Hawk-1',
  imageSource: '/img/mechs/21_PHOENIX_HAWK.jpg',
  tons: 45,
  maxStructure: 14,
  currentStructure: 14,
  originalBaseDice: [HARD_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, COMMAND],
  originalOptionalDice: [DODGE, SOFT_ATTACK],
  optionalDice: [DODGE, SOFT_ATTACK],
  traits: [TRAITS.COMMAND],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const VND_1R = {
  name: 'Vindicator',
  model: 'VND_1R',
  fullName: 'Vindicator-1R',
  imageSource: '/img/mechs/22_VINDICATOR.jpg',
  tons: 45,
  maxStructure: 15,
  currentStructure: 15,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [TRAITS.FAULTY_EJECTION],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const CN9_A = {
  name: 'Centurion',
  model: 'CN9_A',
  fullName: 'Centurion-9A',
  imageSource: '/img/mechs/23_CENTURION.jpg',
  tons: 50,
  maxStructure: 15,
  currentStructure: 15,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, COMMAND],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const ENF_4R = {
  name: 'Enforcer',
  model: 'ENF_4R',
  fullName: 'Enforcer-4R',
  imageSource: '/img/mechs/24_ENFORCER.jpg',
  tons: 50,
  maxStructure: 15,
  currentStructure: 15,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const HBK_4G = {
  name: 'Hunchback',
  model: 'HBK_4G',
  fullName: 'Hunchback-4G',
  imageSource: '/img/mechs/25_HUNCHBACK.jpg',
  tons: 50,
  maxStructure: 16,
  currentStructure: 16,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const TBT_5N = {
  name: 'Trebuchet',
  model: 'TBT_5N',
  fullName: 'Trebuchet-5N',
  imageSource: '/img/mechs/26_TREBUCHET.jpg',
  tons: 50,
  maxStructure: 14,
  currentStructure: 14,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const DV_6M = {
  name: 'Dervish',
  model: 'DV_6M',
  fullName: 'Dervish-6M',
  imageSource: '/img/mechs/27_DERVISH.jpg',
  tons: 55,
  maxStructure: 14,
  currentStructure: 14,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK, DODGE],
  optionalDice: [SOFT_ATTACK, DODGE],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const GRF_1N = {
  name: 'Griffin',
  model: 'GRF_1N',
  fullName: 'Griffin-1N',
  imageSource: '/img/mechs/28_GRIFFIN.jpg',
  tons: 55,
  maxStructure: 16,
  currentStructure: 16,
  originalBaseDice: [HARD_ATTACK, DODGE],
  baseDice: [HARD_ATTACK, DODGE],
  originalOptionalDice: [SOFT_ATTACK, SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK, SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const SHD_2H = {
  name: 'Shadow Hawk',
  model: 'SHD_2H',
  fullName: 'Shadow Hawk-2H',
  imageSource: '/img/mechs/29_SHADOW_HAWK.jpg',
  tons: 55,
  maxStructure: 16,
  currentStructure: 16,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, DODGE],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, DODGE],
  originalOptionalDice: [COMMAND],
  optionalDice: [COMMAND],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const SCP_1N = {
  name: 'Scorpion',
  model: 'SCP_1N',
  fullName: 'Scorpion-1N',
  imageSource: '/img/mechs/30_SCORPION.jpg',
  tons: 55,
  maxStructure: 14,
  currentStructure: 14,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const WVR_6R = {
  name: 'Wolverine',
  model: 'WVR_6R',
  fullName: 'Wolverine-6R',
  imageSource: '/img/mechs/31_WOLVERINE.jpg',
  tons: 55,
  maxStructure: 16,
  currentStructure: 16,
  originalBaseDice: [HARD_ATTACK, COMMAND, DODGE],
  baseDice: [HARD_ATTACK, COMMAND, DODGE],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [TRAITS.COMMAND],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 2,
  originalTargets: 2,
  destroyed: false
}

export const DRG_1N = {
  name: 'Dragon',
  model: 'DRG_1N',
  fullName: 'Dragon-1N',
  imageSource: '/img/mechs/32_DRAGON.jpg',
  tons: 60,
  maxStructure: 17,
  currentStructure: 17,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const OSR_2C = {
  name: 'Ostroc',
  model: 'OSR_2C',
  fullName: 'Ostroc-2C',
  imageSource: '/img/mechs/33_OSTROC.jpg',
  tons: 60,
  maxStructure: 16,
  currentStructure: 16,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK, HARD_ATTACK],
  optionalDice: [SOFT_ATTACK, HARD_ATTACK],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const OTL_4D = {
  name: 'Ostsol',
  model: 'OTL_4D',
  fullName: 'Ostsol-4D',
  imageSource: '/img/mechs/34_OSTSOL.jpg',
  tons: 60,
  maxStructure: 16,
  currentStructure: 16,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK, DODGE],
  optionalDice: [SOFT_ATTACK, DODGE],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const QKD_4G = {
  name: 'Quickdraw',
  model: 'QKD_4G',
  fullName: 'Quickdraw-4G',
  imageSource: '/img/mechs/35_QUICKDRAW.jpg',
  tons: 60,
  maxStructure: 15,
  currentStructure: 15,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, DODGE],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const RFL_3N = {
  name: 'Rifleman',
  model: 'RFL_3N',
  fullName: 'Rifleman-3N',
  imageSource: '/img/mechs/36_RIFLEMAN.jpg',
  tons: 60,
  maxStructure: 15,
  currentStructure: 15,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK, SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK, SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const CPLT_C1 = {
  name: 'Catapult',
  model: 'CPLT_C1',
  fullName: 'Catapult-C1',
  imageSource: '/img/mechs/37_CATAPULT.jpg',
  tons: 65,
  maxStructure: 18,
  currentStructure: 18,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [TRAITS.FAULTY_EJECTION],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const CRD_3R = {
  name: 'Crusader',
  model: 'CRD_3R',
  fullName: 'Crusader-3R',
  imageSource: '/img/mechs/38_CRUSADER.jpg',
  tons: 65,
  maxStructure: 20,
  currentStructure: 20,
  originalBaseDice: [HARD_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, COMMAND],
  originalOptionalDice: [SOFT_ATTACK, HARD_ATTACK],
  optionalDice: [SOFT_ATTACK, HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const JM6_S = {
  name: 'Jagermech',
  model: 'JM6_S',
  fullName: 'Jagermech-6S',
  imageSource: '/img/mechs/39_JAGERMECH.jpg',
  tons: 65,
  maxStructure: 13,
  currentStructure: 13,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const TDR_5S = {
  name: 'Thunderbolt',
  model: 'TDR_5S',
  fullName: 'Thunderbolt-5S',
  imageSource: '/img/mechs/40_THUNDERBOLT.jpg',
  tons: 65,
  maxStructure: 21,
  currentStructure: 21,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const ARC_2R = {
  name: 'Archer',
  model: 'ARC_2R',
  fullName: 'Archer-2R',
  imageSource: '/img/mechs/41_ARCHER.jpg',
  tons: 70,
  maxStructure: 21,
  currentStructure: 21,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [COMMAND, HARD_ATTACK],
  optionalDice: [COMMAND, HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const GHR_5H = {
  name: 'Grasshopper',
  model: 'GHR_5H',
  fullName: 'Grasshopper-5H',
  imageSource: '/img/mechs/42_GRASSHOPPER.jpg',
  tons: 70,
  maxStructure: 21,
  currentStructure: 21,
  originalBaseDice: [HARD_ATTACK, DODGE, COOLING],
  baseDice: [HARD_ATTACK, DODGE, COOLING],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const WHM_6R = {
  name: 'Warhammer',
  model: 'WHM_6R',
  fullName: 'Warhammer-6R',
  imageSource: '/img/mechs/43_WARHAMMER.jpg',
  tons: 70,
  maxStructure: 18,
  currentStructure: 18,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK],
  baseDice: [HARD_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [HARD_ATTACK, COMMAND],
  optionalDice: [HARD_ATTACK, COMMAND],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const MAD_3R = {
  name: 'Marauder',
  model: 'MAD_3R',
  fullName: 'Marauder-3R',
  imageSource: '/img/mechs/44_MARAUDER.jpg',
  tons: 75,
  maxStructure: 20,
  currentStructure: 20,
  originalBaseDice: [HARD_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, COMMAND],
  originalOptionalDice: [HARD_ATTACK, SOFT_ATTACK],
  optionalDice: [HARD_ATTACK, SOFT_ATTACK],
  traits: [TRAITS.COMMAND],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const ON_1K = {
  name: 'Orion',
  model: 'ON_1K',
  fullName: 'Orion-1K',
  imageSource: '/img/mechs/45_ORION.jpg',
  tons: 75,
  maxStructure: 23,
  currentStructure: 23,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 3,
  originalTargets: 3,
  destroyed: false
}

export const AWS_8Q = {
  name: 'Awesome',
  model: 'AWS_8Q',
  fullName: 'Awesome-8Q',
  imageSource: '/img/mechs/46_AWESOME.jpg',
  tons: 80,
  maxStructure: 24,
  currentStructure: 24,
  originalBaseDice: [HARD_ATTACK, HARD_ATTACK, COOLING],
  baseDice: [HARD_ATTACK, HARD_ATTACK, COOLING],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const CGR_1A1 = {
  name: 'Charger',
  model: 'CGR_1A1',
  fullName: 'Charger-1A1',
  imageSource: '/img/mechs/47_CHARGER.jpg',
  tons: 80,
  maxStructure: 19,
  currentStructure: 19,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK, DODGE],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const GOL_1H = {
  name: 'Goliath',
  model: 'GOL_1H',
  fullName: 'Goliath-1H',
  imageSource: '/img/mechs/48_GOLIATH.jpg',
  tons: 80,
  maxStructure: 24,
  currentStructure: 24,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const VTR_9B = {
  name: 'Victor',
  model: 'VTR_9B',
  fullName: 'Victor-9B',
  imageSource: '/img/mechs/49_VICTOR.jpg',
  tons: 80,
  maxStructure: 20,
  currentStructure: 20,
  originalBaseDice: [HARD_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, COMMAND],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const ZEU_6S = {
  name: 'Zeus',
  model: 'ZEU_6S',
  fullName: 'Zeus-6S',
  imageSource: '/img/mechs/50_ZEUS.jpg',
  tons: 80,
  maxStructure: 20,
  currentStructure: 20,
  originalBaseDice: [HARD_ATTACK, HARD_ATTACK],
  baseDice: [HARD_ATTACK, HARD_ATTACK],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const BLR_1G = {
  name: 'Battlemaster',
  model: 'BLR_1G',
  fullName: 'Battlemaster-1G',
  imageSource: '/img/mechs/51_BATTLEMASTER.jpg',
  tons: 85,
  maxStructure: 24,
  currentStructure: 24,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, COMMAND],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const STK_3F = {
  name: 'Stalker',
  model: 'STK_3F',
  fullName: 'Stalker-3F',
  imageSource: '/img/mechs/52_STALKER.jpg',
  tons: 85,
  maxStructure: 23,
  currentStructure: 23,
  originalBaseDice: [SOFT_ATTACK, SOFT_ATTACK],
  baseDice: [SOFT_ATTACK, SOFT_ATTACK],
  originalOptionalDice: [HARD_ATTACK, HARD_ATTACK],
  optionalDice: [HARD_ATTACK, HARD_ATTACK],
  traits: [TRAITS.URBAN_COMBAT],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const CP_10_Z = {
  name: 'Cyclops',
  model: 'CP_10_Z',
  fullName: 'Cyclops-10Z',
  imageSource: '/img/mechs/53_CYCLOPS.jpg',
  tons: 90,
  maxStructure: 20,
  currentStructure: 20,
  originalBaseDice: [HARD_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, COMMAND],
  originalOptionalDice: [HARD_ATTACK],
  optionalDice: [HARD_ATTACK],
  traits: [TRAITS.COMMAND],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const BNC_3E = {
  name: 'Banshee',
  model: 'BNC_3E',
  fullName: 'Banshee-3E',
  imageSource: '/img/mechs/54_BANSHEE.jpg',
  tons: 95,
  maxStructure: 26,
  currentStructure: 26,
  originalBaseDice: [HARD_ATTACK, SOFT_ATTACK, COMMAND],
  baseDice: [HARD_ATTACK, SOFT_ATTACK, COMMAND],
  originalOptionalDice: [SOFT_ATTACK],
  optionalDice: [SOFT_ATTACK],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

export const AS7_D = {
  name: 'Atlas',
  model: 'AS7_D',
  fullName: 'Atlas-7D',
  imageSource: '/img/mechs/55_ATLAS.jpg',
  tons: 100,
  maxStructure: 30,
  currentStructure: 30,
  originalBaseDice: [HARD_ATTACK, HARD_ATTACK, HARD_ATTACK],
  baseDice: [HARD_ATTACK, HARD_ATTACK, HARD_ATTACK],
  originalOptionalDice: [],
  optionalDice: [],
  traits: [],
  lance: null,
  index: null,
  heat: 0,
  dodge: 0,
  assignedTargets: [],
  damageAimed: 0,
  heatAimed: 0,
  targets: 4,
  originalTargets: 4,
  destroyed: false
}

// mechs
export const MECHS = {
  LCT_1V,
  WSP_1A,
  STG_3R,
  COM_2D,
  JVN_10N,
  SDR_5V,
  UM_R60,
  VLK_QA,
  FS9_H,
  JR7_D,
  OTT_7J,
  PNT_9R,
  ASN_21,
  CDA_2A,
  CLNT_2_3T,
  HER_2S,
  VL_2T,
  WTH_1,
  BJ_1,
  HCT_3F,
  PHX_1,
  VND_1R,
  CN9_A,
  ENF_4R,
  HBK_4G,
  TBT_5N,
  DV_6M,
  GRF_1N,
  SHD_2H,
  SCP_1N,
  WVR_6R,
  DRG_1N,
  OSR_2C,
  OTL_4D,
  QKD_4G,
  RFL_3N,
  CPLT_C1,
  CRD_3R,
  JM6_S,
  TDR_5S,
  ARC_2R,
  GHR_5H,
  WHM_6R,
  MAD_3R,
  ON_1K,
  AWS_8Q,
  CGR_1A1,
  GOL_1H,
  VTR_9B,
  ZEU_6S,
  BLR_1G,
  STK_3F,
  CP_10_Z,
  AS7_D
}