export const FAULTY_EJECTION = 'FAULTY_EJECTION'
export const URBAN_COMBAT = 'URBAN_COMBAT'
export const EFFICIENT_EJECTION = 'EFFICIENT_EJECTION'
export const COMMAND = 'COMMAND'

export const TRAITS = {
  FAULTY_EJECTION,
  URBAN_COMBAT,
  EFFICIENT_EJECTION,
  COMMAND
}